"use strict";

const RARITIES = Object.freeze(["common", "uncommon", "rare", "epic", "legendary", "mythic", "celestial"]);
const freeze = (value) => { if (!value || typeof value !== "object" || Object.isFrozen(value)) return value; Object.freeze(value); for (const child of Object.values(value)) freeze(child); return value; };
const EQUIPMENT_ECONOMY_CONFIG = freeze({
  repairRarityMultipliers: { common: 1, uncommon: 1.15, rare: 1.35, epic: 1.65, legendary: 2, mythic: 2.5, celestial: 3 },
  enhancementRarityMultipliers: { common: 1, uncommon: 1.25, rare: 1.6, epic: 2.2, legendary: 3, mythic: 4, celestial: 5.5 },
  selfRepair: { maxSuccessChance: 75, maxBonusChance: 15, failureConsumptionFraction: 0.5 },
  scrapYieldRanges: {
    weapon: { common: [5, 10], uncommon: [10, 18], rare: [18, 32], epic: [32, 55], legendary: [55, 90], mythic: [90, 150], celestial: [150, 250] },
    armor: { common: [4, 8], uncommon: [8, 14], rare: [14, 26], epic: [26, 44], legendary: [44, 72], mythic: [72, 120], celestial: [120, 200] },
    accessory: { common: [3, 6], uncommon: [6, 12], rare: [12, 21], epic: [21, 36], legendary: [36, 58], mythic: [58, 98], celestial: [98, 162] },
  },
  enhancement: { min: 0, max: 10 },
});
function economyError(code, message) { const error = new Error(message); error.code = code; return error; }
function value(item, camel, snake) { return item?.[camel] ?? item?.[snake]; }
function rarity(value) { if (!RARITIES.includes(value)) throw economyError("INVALID_RARITY", "rarity is not valid."); return value; }
function scrapCategory(subtype) { if (subtype === "weapon") return "weapon"; if (["helmet", "chest", "gloves", "legs", "boots"].includes(subtype)) return "armor"; if (subtype === "accessory") return "accessory"; throw economyError("INVALID_ITEM_SUBTYPE", "This equipment subtype cannot be scrapped."); }
function quoteEquipmentScrap({ rarity: itemRarity, subtype }) { const validRarity = rarity(itemRarity); const [minimum, maximum] = EQUIPMENT_ECONOMY_CONFIG.scrapYieldRanges[scrapCategory(subtype)][validRarity]; return { minimum, maximum, rarity: validRarity, subtype }; }
function rollEquipmentScrapYield({ rarity: itemRarity, subtype, rng }) { const quote = quoteEquipmentScrap({ rarity: itemRarity, subtype }); const roll = typeof rng === "function" ? rng() : NaN; if (typeof roll !== "number" || !Number.isFinite(roll) || roll < 0 || roll >= 1) throw economyError("INVALID_RNG_ROLL", "RNG must return a number from zero inclusive to one exclusive."); return quote.minimum + Math.floor(roll * (quote.maximum - quote.minimum + 1)); }
function durabilityState(item) { const durabilityCurrent = value(item, "durabilityCurrent", "durability_current"); const durabilityMax = value(item, "durabilityMax", "durability_max"); if (durabilityCurrent == null && durabilityMax == null) return null; if (!Number.isInteger(durabilityCurrent) || !Number.isInteger(durabilityMax) || durabilityMax <= 0 || durabilityCurrent < 0 || durabilityCurrent > durabilityMax) throw economyError("INVALID_DURABILITY", "Durability must be a valid current/max pair."); return { durabilityCurrent, durabilityMax, conditionPercent: durabilityCurrent / durabilityMax * 100, missingDurability: durabilityMax - durabilityCurrent, missingPercent: (durabilityMax - durabilityCurrent) / durabilityMax * 100, broken: durabilityCurrent === 0 }; }
function getDurabilityValueMultiplier(item) { const state = durabilityState(item); if (!state) return null; if (!state.durabilityCurrent) return .2; if (state.conditionPercent >= 90) return 1; if (state.conditionPercent >= 75) return .9; if (state.conditionPercent >= 50) return .75; if (state.conditionPercent >= 25) return .55; return .35; }
function ceilWithRarityMultiplier(value, multiplier, factor = 1, divisor = 1) { return Math.ceil(value * Math.round(multiplier * 100) * factor / (100 * divisor)); }
function quoteSelfRepair(item, extraScrap = 0) { const state = durabilityState(item); if (!state) throw economyError("ITEM_NOT_DURABLE", "This item has no durability."); if (!state.missingDurability) throw economyError("ITEM_NOT_DAMAGED", "This item is already at full durability."); const multiplier = EQUIPMENT_ECONOMY_CONFIG.repairRarityMultipliers[rarity(item?.rarity)]; const baseScrapCost = Math.max(1, ceilWithRarityMultiplier(state.missingDurability, multiplier, 1, 10)); if (!Number.isSafeInteger(extraScrap) || extraScrap < 0 || extraScrap > baseScrapCost) throw economyError("INVALID_EXTRA_SCRAP", "extraScrap must be between zero and the base cost."); const baseSuccessChance = state.missingPercent <= 10 ? 75 : state.missingPercent <= 25 ? 65 : state.missingPercent <= 50 ? 50 : 35; const bonusChance = Math.floor(EQUIPMENT_ECONOMY_CONFIG.selfRepair.maxBonusChance * extraScrap / baseScrapCost); const finalSuccessChance = Math.min(EQUIPMENT_ECONOMY_CONFIG.selfRepair.maxSuccessChance, baseSuccessChance + bonusChance); const successScrapConsumed = baseScrapCost + extraScrap; return { durable: true, broken: state.broken, ...state, baseSuccessChance, bonusChance, finalSuccessChance, baseScrapCost, extraScrap, successScrapConsumed, failureScrapConsumed: Math.max(1, Math.ceil(successScrapConsumed * EQUIPMENT_ECONOMY_CONFIG.selfRepair.failureConsumptionFraction)) }; }
function selfRepairBoostOptions(item) { const base = quoteSelfRepair(item, 0).baseScrapCost; return [...new Set([0, Math.floor(base * .25), Math.floor(base * .5), Math.floor(base * .75), base])].map((extraScrap) => quoteSelfRepair(item, extraScrap)); }
function quoteForgeRepair(item) { const state = durabilityState(item); if (!state) throw economyError("ITEM_NOT_DURABLE", "This item has no durability."); if (!state.missingDurability) throw economyError("ITEM_NOT_DAMAGED", "This item is already at full durability."); return { durable: true, ...state, walletCreditCost: Math.max(1, ceilWithRarityMultiplier(state.missingDurability, EQUIPMENT_ECONOMY_CONFIG.repairRarityMultipliers[rarity(item?.rarity)], 2)), finalDurability: state.durabilityMax }; }
function quoteEnhancement(item) { const currentEnhancement = value(item, "enhancementLevel", "enhancement_level"); if (!Number.isInteger(currentEnhancement) || currentEnhancement < EQUIPMENT_ECONOMY_CONFIG.enhancement.min || currentEnhancement > EQUIPMENT_ECONOMY_CONFIG.enhancement.max) throw economyError("INVALID_ENHANCEMENT", "Item enhancement is not valid."); const itemRarity = rarity(item?.rarity); const maxed = currentEnhancement === EQUIPMENT_ECONOMY_CONFIG.enhancement.max; const targetEnhancement = maxed ? null : currentEnhancement + 1; return { rarity: itemRarity, currentEnhancement, targetEnhancement, maxed, walletCreditCost: maxed ? null : Math.ceil(100 * targetEnhancement ** 2 * EQUIPMENT_ECONOMY_CONFIG.enhancementRarityMultipliers[itemRarity]) }; }
module.exports = { RARITIES, EQUIPMENT_ECONOMY_CONFIG, scrapCategory, quoteEquipmentScrap, rollEquipmentScrapYield, durabilityState, getDurabilityValueMultiplier, ceilWithRarityMultiplier, quoteSelfRepair, selfRepairBoostOptions, quoteForgeRepair, quoteEnhancement };
