export type RealmClass = Readonly<{ key: string; display_name: string; description: string; weapon_affinities: readonly string[]; contributions: Readonly<Record<string, number>>; specializations: readonly RealmSpecialization[] }>;
export type RealmSpecialization = Readonly<{ key: string; parent_class_key: string; display_name: string; description: string; combat_identity: string; future_stat_direction: readonly string[]; skill_themes: readonly string[]; tradeoff: string; contributions: Readonly<Record<string, number>> }>;
export const STAT_KEYS: readonly string[];
export const CLASS_KEYS: readonly string[];
export const SPECIALIZATION_KEYS: readonly string[];
export const PHASE4D_CLASS_CONTENT_VERSION: number;
export const PHASE4D_CLASS_CONTENT_KEY: string;
export const PHASE4D_CLASS_CONTENT_HASH: string;
export const PHASE4D_CLASS_CONTENT_CANONICAL: string;
export const PHASE4D_CLASS_CONTENT: Readonly<{ content_version: number; content_key: string; classes: readonly RealmClass[] }>;
export function contributions(values?: Record<string, number>): Readonly<Record<string, number>>;
export function canonicalSerialize(content: unknown): string;
export const RARITIES: readonly string[];
export const EQUIPMENT_ECONOMY_CONFIG: Readonly<Record<string, unknown>>;
export type EconomyItem = { rarity: string; durabilityCurrent?: number | null; durabilityMax?: number | null; durability_current?: number | null; durability_max?: number | null; enhancementLevel?: number; enhancement_level?: number };
export function scrapCategory(subtype: string): "weapon" | "armor" | "accessory";
export function quoteEquipmentScrap(input: { rarity: string; subtype: string }): Readonly<{ minimum: number; maximum: number; rarity: string; subtype: string }>;
export function rollEquipmentScrapYield(input: { rarity: string; subtype: string; rng: () => number }): number;
export function durabilityState(item: EconomyItem): Readonly<Record<string, number | boolean>> | null;
export function getDurabilityValueMultiplier(item: EconomyItem): number | null;
export function ceilWithRarityMultiplier(value: number, multiplier: number, factor?: number, divisor?: number): number;
export function quoteSelfRepair(item: EconomyItem, extraScrap?: number): Readonly<Record<string, number | boolean>>;
export function selfRepairBoostOptions(item: EconomyItem): readonly Readonly<Record<string, number | boolean>>[];
export function quoteForgeRepair(item: EconomyItem): Readonly<Record<string, number | boolean>>;
export function quoteEnhancement(item: EconomyItem): Readonly<Record<string, string | number | boolean | null>>;
