"use strict";
function freeze(value) { if (!value || typeof value !== "object" || Object.isFrozen(value)) return value; Object.freeze(value); for (const child of Object.values(value)) freeze(child); return value; }
function range(range, label) { if (!Number.isSafeInteger(range?.min) || !Number.isSafeInteger(range?.max) || range.min <= 0 || range.max < range.min) throw new TypeError(`Invalid ${label} reward range.`); }
function validateVeyraEncounter(e) { if (!e || e.world !== "veyra" || !["normal", "miniboss"].includes(e.encounterType)) throw new TypeError("Invalid Veyra encounter metadata."); if (!Number.isInteger(e.level) || e.level < 1 || e.maxHp <= 0 || e.stats?.hp !== e.maxHp || e.stats.power < 0 || e.stats.defense < 0) throw new TypeError(`Invalid Veyra encounter stats: ${e?.key || "unknown"}.`); if (!Number.isInteger(e.weapon?.minDamage) || !Number.isInteger(e.weapon?.maxDamage) || e.weapon.minDamage <= 0 || e.weapon.maxDamage < e.weapon.minDamage || e.weapon.recoveryMs <= 0) throw new TypeError(`Invalid Veyra encounter weapon: ${e.key}.`); range(e.rewards?.xp, "XP"); range(e.rewards?.credits, "Credit"); range(e.rewards?.scrap, "Scrap"); if (e.encounterType === "normal" && (e.rewards.scrap.min !== 2 || e.rewards.scrap.max !== 7)) throw new TypeError("Normal Veyra Scrap must be 2–7."); if (e.encounterType === "miniboss" && (e.rewards.scrap.min !== 8 || e.rewards.scrap.max !== 18)) throw new TypeError("Miniboss Veyra Scrap must be 8–18."); return e; }
function enemy(key, displayName, encounterType, level, hp, power, defense, crit, accuracy, dodge, minDamage, maxDamage, attackName, rewards) { return freeze(validateVeyraEncounter({ key, displayName, world: "veyra", encounterType, level, maxHp: hp, stats: { hp, power, defense, crit_chance: crit, crit_damage: 150, accuracy, dodge, lifesteal: 0, resistance: 0, potency: 0, luck: 0, armor_penetration: 0, damage_reduction: 0, status_chance: 0, cooldown_reduction: 0, execute_threshold: 0, block: 0 }, weapon: { weaponKey: `${key}_attack`, weaponFamily: "natural", minDamage, maxDamage, recoveryMs: 2500 }, attackName, rewards })); }
const normal = { xp: { min: 40, max: 95 }, credits: { min: 20, max: 70 }, scrap: { min: 2, max: 7 } };
const VEYRA_ENCOUNTERS = freeze({ mossback_grazer: enemy("mossback_grazer", "Mossback Grazer", "normal", 1, 72, 7, 5, 3, 0, 2, 4, 7, "Moss Charge", normal), thornjaw_wolf: enemy("thornjaw_wolf", "Thornjaw Wolf", "normal", 2, 84, 9, 6, 5, 1, 6, 5, 9, "Thornjaw Bite", normal), lanternwing_moth: enemy("lanternwing_moth", "Lanternwing Moth", "normal", 3, 76, 9, 5, 4, 3, 10, 4, 8, "Lantern Dust", normal), rootling_ambusher: enemy("rootling_ambusher", "Rootling Ambusher", "normal", 4, 102, 11, 8, 5, 2, 4, 6, 10, "Rootlash", normal), glasshorn_stag: enemy("glasshorn_stag", "Glasshorn Stag", "normal", 5, 118, 12, 10, 6, 2, 7, 7, 11, "Glasshorn Rush", normal), ruinbound_sentinel: enemy("ruinbound_sentinel", "Ruinbound Sentinel", "normal", 7, 152, 14, 15, 4, 3, 2, 8, 13, "Ruin Hammer", normal), whisperbloom_mimic: enemy("whisperbloom_mimic", "Whisperbloom Mimic", "normal", 9, 136, 16, 11, 7, 5, 6, 9, 15, "Whisper Lash", normal), briar_matron: enemy("briar_matron", "Briar Matron", "miniboss", 4, 132, 11, 9, 5, 2, 4, 6, 10, "Briar Lash", { xp: { min: 90, max: 125 }, credits: { min: 55, max: 90 }, scrap: { min: 8, max: 18 } }), old_ironroot: enemy("old_ironroot", "Old Ironroot", "miniboss", 6, 172, 13, 15, 4, 2, 2, 7, 12, "Ironroot Slam", { xp: { min: 115, max: 155 }, credits: { min: 70, max: 110 }, scrap: { min: 8, max: 18 } }), warder_khelt: enemy("warder_khelt", "Warder Khelt", "miniboss", 8, 154, 15, 12, 6, 4, 5, 9, 14, "Khelt Cleave", { xp: { min: 140, max: 185 }, credits: { min: 90, max: 130 }, scrap: { min: 8, max: 18 } }) });
function getVeyraEncounter(key) { const value = VEYRA_ENCOUNTERS[key]; return value ? JSON.parse(JSON.stringify(value)) : null; }
function equipment(itemKey, displayName, subtype, metadata = {}) { return freeze({ itemKey, displayName, itemType: "equipment", subtype, worldKey: "veyra", baseRarity: "common", tradable: true, scrappable: true, durabilityEnabled: true, stackable: false, enabled: true, metadata: freeze({ hunt_drop: true, ...metadata }) }); }
const VEYRA_HUNT_DROP_DEFINITIONS = freeze([equipment("veyra_verdant_edge", "Verdant Edge", "weapon", { weapon_family: "sword" }), equipment("veyra_rootbreaker", "Rootbreaker", "weapon", { weapon_family: "hammer" }), equipment("veyra_thornwake", "Thornwake", "weapon", { weapon_family: "dagger" }), equipment("veyra_stoneheart", "Stoneheart", "weapon", { weapon_family: "greatsword" }), equipment("veyra_shepherds_reach", "Shepherd’s Reach", "weapon", { weapon_family: "bow" }), equipment("veyra_heartwood_covenant", "Heartwood Covenant", "weapon", { weapon_family: "staff" }), equipment("veyra_wildguard_helmet", "Wildguard Helm", "helmet", { set_key: "wildguard" }), equipment("veyra_wildguard_chest", "Wildguard Chestplate", "chest", { set_key: "wildguard" }), equipment("veyra_wildguard_gloves", "Wildguard Gloves", "gloves", { set_key: "wildguard" }), equipment("veyra_wildguard_legs", "Wildguard Legguards", "legs", { set_key: "wildguard" }), equipment("veyra_wildguard_boots", "Wildguard Boots", "boots", { set_key: "wildguard" }), equipment("veyra_pathfinder_helmet", "Pathfinder Hood", "helmet", { set_key: "pathfinder" }), equipment("veyra_pathfinder_chest", "Pathfinder Coat", "chest", { set_key: "pathfinder" }), equipment("veyra_pathfinder_gloves", "Pathfinder Gloves", "gloves", { set_key: "pathfinder" }), equipment("veyra_pathfinder_legs", "Pathfinder Leggings", "legs", { set_key: "pathfinder" }), equipment("veyra_pathfinder_boots", "Pathfinder Boots", "boots", { set_key: "pathfinder" })]);
const VEYRA_HUNT_DROP_BY_KEY = freeze(Object.fromEntries(VEYRA_HUNT_DROP_DEFINITIONS.map((d) => [d.itemKey, d])));
const VEYRA_WEAPON_DROPS = freeze(VEYRA_HUNT_DROP_DEFINITIONS.filter((d) => d.subtype === "weapon")); const VEYRA_ARMOR_DROPS = freeze(VEYRA_HUNT_DROP_DEFINITIONS.filter((d) => d.subtype !== "weapon"));
module.exports = { VEYRA_ENCOUNTERS, getVeyraEncounter, validateVeyraEncounter, VEYRA_HUNT_DROP_DEFINITIONS, VEYRA_HUNT_DROP_BY_KEY, VEYRA_WEAPON_DROPS, VEYRA_ARMOR_DROPS };
